---
- name: "Directory Exists | {{ mariadb_backup_path }}"
  file:
    state: directory
    path: "{{ mariadb_backup_path }}"
    owner: "{{ mariadb_user }}"
    group: wcadmin
    mode: 0775
  when: mariadb_backup_enabled
  tags:
    - directory-structure
    - mariadb
    - backup

- name: Setup Automated Backups 
  cron:
    name: mariadb-backup
    special_time: "{{ mariadb_backup_frequency }}"
    job: "sudo mysqldump {{ database_name | default(project) }} | 7z a -si {{ mariadb_backup_path }}/backup-`date +%Y%m%d%H`.7z"
  when: mariadb_backup_enabled
  tags:
    - mariadb
    - backup
    - using-cron
