---
- name: "Directory Exists | {{ mariadb_runtime_root }}"
  file:
    state: directory
    path: "{{ mariadb_runtime_root }}"
    owner: "{{ mariadb_user }}"
    group: staff
    mode: 0775
  notify: Stop Service | mariadb
  tags:
    - directory-structure
    - runtime-data
    - mariadb

- name: Configure | mariadb | pidfile
  lineinfile:
    state: present
    dest: /etc/mysql/my.cnf
    regexp: '^.*pid-file'
    line: "pid-file = {{ mariadb_pidfile_path }}"
  notify: Reload Service | mariadb
  tags:
    - pidfile
    - service

- name: Configure | mariadb | bind-address
  replace:
    dest: /etc/mysql/my.cnf
    regexp: '^#* *bind-address.*'
    replace: 'bind-address = 0.0.0.0'
  when: mariadb_accepts_external_connections
  notify: Reload Service | mariadb
  tags:
    - networking

- name: Configure | mariadb | replication
  lineinfile:
    state: absent
    dest: /etc/mysql/my.cnf
    regexp: "{{ item }}"
  with_items:
    - '^#* *log_bin'
    - '^#* *log_bin_index'
    - '^#* *expire_logs_days'
    - '^#* *max_binlog_size'
  notify: Reload Service | mariadb
  tags:
    - replication

- name: Configure | mariadb | max_connect_errors
  lineinfile:
    state: present
    dest: /etc/mysql/my.cnf
    regexp: '^#* *max_connect_errors'
    line: 'max_connect_errors = 4294967295'
    insertafter: '\[mysqld\]'
  when: using_load_balancer
  notify:
    - Reload Service | mariadb
    - Start Service | mariadb
  tags:
    - workaround
