---
- name: Preemptively Answer | MariaDB | Root Password
  shell: "debconf-set-selections << 'mariadb-server-10.1 mariadb-server/root_password password {{ database_password | mandatory }}'"
  shell: "debconf-set-selections << 'mariadb-server-10.1 mariadb-server/root_password_again password {{ database_password | mandatory }}'"
  when: mariadb_server

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - mariadb-server
    - python-mysqldb
  when: mariadb_server

- name: Create Database User
  mysql_user:
    state: present
    name: "{{ database_username | default(project) }}"
    password: "{{ database_password | mandatory }}"
    priv: "mysql.*:ALL/{{ project}}.*:ALL"
    host: "%"
  when: mariadb_server

- name: Service Stopped | mariadb
  service:
    name: mysql
    state: stopped
  when: mariadb_server
  tags:
    - disruptive

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - mariadb-client
  when: mariadb_client
