---
- name: Configure | mariadb | general log
  lineinfile:
    state: present
    dest: /etc/mysql/my.cnf
    regexp: '^.*general_log_file'
    line: "general_log_file = {{ mariadb_general_log_path }}"
  notify: Reload Service | mariadb
  tags:
    - configuration
    - precise-configuration
    - logging
    - mariadb

- name: "File is Writable | {{ mariadb_general_log_path }}"
  file:
    state: touch
    path: "{{ mariadb_general_log_path }}"
    owner: "{{ mariadb_user }}"
    group: wcadmin
    mode: 0664
  tags:
    - permissions
    - logging
    - mariadb

- name: Configure | mariadb | slow query log
  lineinfile:
    state: present
    dest: /etc/mysql/my.cnf
    regexp: '^.*slow_query_log_file'
    line: "slow_query_log_file = {{ mariadb_slow_query_log_path }}"
  notify: Reload Service | mariadb
  tags:
    - configuration
    - precise-configuration
    - logging
    - mariadb

- name: "File is Writable | {{ mariadb_slow_query_log_path }}"
  file:
    state: touch
    path: "{{ mariadb_slow_query_log_path }}"
    owner: "{{ mariadb_user }}"
    group: wcadmin
    mode: 0664
  tags:
    - permissions
    - logging
    - mariadb
